import { Provider } from "../../context/ThemeContext"
import "../global.css"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head><link rel="icon" href="/favicon.ico" /><title>Portfolio</title></head>
      <Provider>
        <body className="w-screen h-screen">{children}</body>
      </Provider>
    </html>
  )
}
